### ISSUE TITLE
CKEditor friert bei Neusortierung über mblock (über die Pfeile) ein.

### ISSUE THREAD

**Issue by seeyouonline** [FriendsOfREDAXO/ckeditor#10]
Die Sortierung der mblock Blöcke via Drag & Drop funktioniert seit dem letzten Update einwandfrei.
Leider klappt es noch nicht wenn die Sortierung über die Pfeile gemacht wird.

**Comment by pschuchmann** [comment]
@seeyouonline ich sehe es mir mal an. Drag & Drop funktioniert soweit erstmal als Lösung für dich?

**Comment by NGWNGW** [comment]
Kann ich bestätigen. Drag&Drop funktioniert, Pfeiltasten jedoch nicht.

**Comment by schwampf** [comment]
Liegt vermutlich an der redaxo.js

Versucht mal ab Zeile 307 den Block

```
$(document).on('rex:change', function (e, container) {
 
let textarea = $(container).find('textarea');
let editor = $(container).find('.cke');
let id = $(editor).attr('id').replace('cke_', '');
 
CKEDITOR.instances[id].destroy();
rex_ckeditor_init(textarea);

});
```

zu ändern in 

```
$(document).on('rex:change', function (e, container) {

  let textarea = $(container).find('textarea');
  let editor = $(container).find('.cke');
  if(editor.length > 0) {
    let id = $(editor).attr('id').replace('cke_', '');

    CKEDITOR.instances[id].destroy();
    rex_ckeditor_init(textarea);
  }
  

});
```

**Comment by pschuchmann** [comment]
@schwampf Ich bin endlich zum Testen gekommen und bei mir hat das leider keinerlei Effekt gezeigt, dass Problem bleibt weiterhin bestehen. Hattest du sonst noch Anpassungen am Init vorgenommen?

**Comment by NGWNGW** [comment]
Bei mir brachte die Änderung ebenfalls keine Verbesserung (neueste MForm / MBlock Version). 

Was mir aufgefallen ist: Beim Ändern der Reihenfolge über die Pfeile wird einer der Textareas eine seltsame ID vergeben. Liegt hier evtl. irgendwo der Fehler?

`<textarea id="REX_INPUT_VALUE10text" name="REX_INPUT_VALUE[1][0][text]" class="form-control ckeditor ckeditor-smartstrip" data-ckeditor-profile="custom" style="visibility: hidden; display: none;"></textarea>`

statt

`<textarea id="ckeditor086e673bf9c7d" name="REX_INPUT_VALUE[1][0][text]" class="form-control ckeditor ckeditor-smartstrip" data-ckeditor-profile="custom" style="visibility: hidden; display: none;"></textarea>`

**Comment by pschuchmann** [comment]
Liegt im Bereich des Möglichen 😊 Mit der vergebenen ID wird das CKEditor Element intern abgelegt und das scheint er deswegen nicht mehr holen zu können. Ich versuche die Tage nochmal danach zu sehen.

**Comment by iceman-fx** [comment]
Ich glaube, dass ich dafür jetzt eine Lösung habe.

ab Zeile 307 dies:

`$(document).on('rex:change', function (e, container) {
 
  let textarea = $(container).find('textarea');
  let editor = $(container).find('.cke');
  let id = $(editor).attr('id').replace('cke_', '');
 
  CKEDITOR.instances[id].destroy();
  rex_ckeditor_init(textarea);

});`

tauschen mit:

`$(document).on('rex:change', function (e, container) {
	
	container.parent('div').find('textarea.ckeditor').each(function(){
		let ed = $(this).next('.cke');
		
		if (ed.length > 0) {
			let id = $(ed).attr('id').replace('cke_', '');		
			
			CKEDITOR.instances[id].destroy();
			rex_ckeditor_init($(this));
		}
	})
});`

Bitte mal testen und wenn es passen sollte, in das Addon übernehmen.

**Comment by iceman-fx** [comment]
In der neuen Installerversion behoben.
