### ISSUE TITLE
Linkmap mehrsprachig

### ISSUE THREAD

**Issue by fietstouring** [FriendsOfREDAXO/ckeditor#11]
Anscheinend berücksichtigt der CKEditor nicht in welcher Sprache man sich befindet beim Öffnen der Linkmap

**Comment by fietstouring** [comment]
```
onClick: function () {
            rex_ckeditor_get_link_from_linkmap();
   }
```

Bei diesem Aufruf müsste man die Sprache mitschicken und die Funktion müsste sie dann an openLinkMap(id, param) weitergeben. Kriegt man die clang id da irgendwie über JS?

**Comment by fietstouring** [comment]
Man könnte in die Textarea ein `data-ckeditor-lang="sprach_id"` dazugeben und das dann auslesen

**Comment by fietstouring** [comment]
```
let ckeditorLang = '';
let searchParams = new URLSearchParams(window.location.search);

    // get clang from url param
    if (searchParams.has('clang')) {
       ckeditorLang = searchParams.get('clang');
    } else 

    // get redaxo lang from global settings
    if ( $('body').attr('id').indexOf("rex-page-global-settings-settings-clang") > -1 ) {
      ckeditorLang = $('body').attr('id').slice(39);
    } 

```

**Comment by pschuchmann** [comment]
Inwiefern meinst du in welcher Sprache sich man befindet? Du meinst im englischen Backend wird aktuell die deutsche Linkmap ausgegeben zum Beispiel?!

**Comment by fietstouring** [comment]
Ja genau! Über den clang param lässt sich das leicht auslesen, zumindest in der Struktur oder wenn man ckeditor in metainfos verwendet. Bei den Addons weiß ich nicht obs eine allgemeine Lösung gibt bzw. auch bei einem ckeditor in einer yform Tabelle, das hab ich mir noch nicht angesehen.

**Comment by pschuchmann** [comment]
Da dürfte es ähnlich sein. Könntest du bitte prüfen, wie das zum Beispiel das REX_LINK Widget macht?

**Comment by fietstouring** [comment]
Ja die clang wird da ja einfach als param mitgegeben und an die JS function übergeben die die Linkmap öffnet, das kommt aber von PHP bei den Redaxo-Widgets, während es beim CkEditor ja über JS kommen muss.

**Comment by fietstouring** [comment]
```
let ckeditorLang = '1';

function rex_ckeditor_get_link_from_linkmap() {
  var linkMap = openLinkMap(1, '&clang=' + ckeditorLang);

  $(linkMap).on('rex:selectLink', function (e, linkurl, linktext) {
    e.preventDefault();
    linkMap.close();

    jQuery('.rex-url input').val(linkurl);
    jQuery('.rex-protocol option:last').prop('selected', true);
  });
}
```

damit funktioniert das

**Comment by pschuchmann** [comment]
Ich sehe zu, dass ich das im nächsten Release einbaue, danke dir!

**Comment by danspringer** [comment]
Kommt da evtl noch was? :-D

**Comment by skerbis** [comment]
https://github.com/FriendsOfREDAXO/ckeditor/releases/tag/4.20.2-beta1
