### ISSUE TITLE
stylesheetparser permanent inkludieren

### ISSUE THREAD

**Issue by iceman-fx** [FriendsOfREDAXO/ckeditor#6]
Hi,
es wäre toll, wenn das Plugin stylesheetparser immer gleich mit im Package inkludiert wäre.
Das würde viel Zeit ersparen, dieses nach einem Update manuell nachinstallieren zu müssen.

**Comment by pschuchmann** [comment]
Hey,

standardmäßig wird immer der CKE Full ausgeliefert. Bei einem Update wird auch jedes Mal wieder das assets Verzeichnis gelöscht um den Vendor in der neuen Version bereitzustellen. 

Um eigene Plugins updatesicher einzubinden, kannst du wie folgt vorgehen.

Aus der Doku:

> 
> Eigene CKEditor Plugins benutzen
> Eigene Plugins werden einfach in dass project Addon dort unter /install/ckeditor/plugins/ gelegt. Diese werden automatisch in das CKEditor Plugin Verzeichnis kopiert bei Install, Reinstall und Update des CKEditor AddOns und stehen so immer zur Verfügung. Im Profil muss man dann noch unter extraPlugins das Plugin mit auflisten (durch Komma getrennt wenn mehrere). Alles weitere sollte man der Doku des Plugins entnehmen... ;)
> 
> Bitte beachten: Sollten nach einem Update die eigene Plugins nicht kompatibel sein mit der neusten CKEditor Version kann der Editor unter Umständen nicht mehr geladen werden. Abhilft schafft hier die betreffenden Plugins im Profil unter extraPlugins zu entfernen.

>
